### ISSUE TITLE
403 error in Menus

### ISSUE THREAD

**Issue by BurtNL** [joomla/joomla-cms#10518]
#### Steps to reproduce the issue
Install latest staging (but issue may be present in earlier versions).
Install multilanguage functionality (but may not be related to issue).
Clear browsercache and login in backend.
Go to Menu > Add New Menu Item (of any Menu Type).
Then just click Cancel.

#### Expected result
View all menu items.

#### Actual result
You will see a '403 You are not authorised to view this resource'.

![screen shot 2016-05-16 at 14 02 20](https://issues.joomla.org/uploads/1/85243c0edb7fda0b12e0446b0e538eae.jpg)

#### System information (as much as possible)
Windows 10 / WAMP

#### Additional comments
This issue can be reproduced via this URL:
/administrator/index.php?option=com_menus&view=items&menutype=

Expected in URL:
administrator/index.php?option=com_menus&view=items&menutype=*

**Comment by andrepereiradasilva** [comment]
i think this is already solved. apply this patch https://github.com/joomla/joomla-cms/pull/10460

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10518">issues.joomla.org/joomla-cms/10518</a>.</sub>

**Comment by brianteeman** [comment]
Just updated my staging and its ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10518">issues.joomla.org/joomla-cms/10518</a>.</sub>

**Comment by BurtNL** [comment]
It looks like this issue still exists. I have applied patch #10460 on the latest staging and can still reproduce this 403 error.
I will try to find the scenario in which this error occurs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10518">issues.joomla.org/joomla-cms/10518</a>.</sub>

**Comment by brianteeman** [comment]
Please do - I saw the error but now cant repeat it

On 16 May 2016 at 21:26, BurtNL <notifications@github.com> wrote:

> It looks like this issue still exists. I have applied patch #10460
> <https://github.com/joomla/joomla-cms/pull/10460> on the latest staging
> and can still reproduce this 403 error.
> I will try to find the scenario in which this error occurs.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10518
> <https://issues.joomla.org/tracker/joomla-cms/10518>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/10518#issuecomment-219537254>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by BurtNL** [comment]
@brianteeman, yes, it is hard to repeat, the problem does not seem to occur every time.

This is what I have tried:
- clear Joomla cache
- log out
- clear browser cache
- login
- go to Menu > All Menu Items (just to show them)
- then: Menu > Add Menu Item (to any menu type)
- click cancel

This may or may not show the error, because it does not occur always.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10518">issues.joomla.org/joomla-cms/10518</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i crested https://github.com/joomla/joomla-cms/pull/10460 and https://github.com/joomla/joomla-cms/pull/10459 to solve the menu issues.

Please test if with both patches applied you still have issues.

**Comment by BurtNL** [comment]
Cleared Joomla cache and browser cache frequently, logged in and out multiple times, looks good with both patches applied.
I can not reproduce this issue again now. Hope these patches are merged into staging soon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10518">issues.joomla.org/joomla-cms/10518</a>.</sub>

**Comment by andrepereiradasilva** [comment]
test them and mark them as tested with success.
more tests will probably help get them merged :wink:

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10518">issues.joomla.org/joomla-cms/10518</a>

**Comment by infograf768** [comment]
Closed as there are patches.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10518">issues.joomla.org/joomla-cms/10518</a>.</sub>
