### ISSUE TITLE
Language installed by discover cannot be uninstalled

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#12976]
If you install a language using the discover method then it can never be uninstalled because the discover method doesnt not install the package and we have something to prevent you uninstalling a language

>A language should always have been installed as a package. 
To uninstall a language, filter type by package and uninstall the package.

**Comment by mbabker** [comment]
This whole process is flawed.  If we really want to block uninstalling individual extensions that are part of a package, we need to add data to the extension records indicating this parent/child relationship and have this be a configurable behavior via the API.

**Comment by Bakual** [comment]
I never understood why language packs should only be able to be uninstalled as a package. Imho they should behave the same as other packages do.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/commit/33a9b82b00734d913bcd6d2568b4bef7458a3ff9

Ask JM.

**Comment by infograf768** [comment]
See
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=29604&start=0

**Comment by mbabker** [comment]
Or https://developer.joomla.org/joomlacode-archive/issue-29604.html if you're trying to avoid a hunk of crap software package 😉 

The issue there is a legitimate one, but the fix needs improvement to work for all package extensions.  You are correct in that the distributed language packages are always package extensions composing of the individual language extensions.  However, if those individual language extensions are installed separate from the complete package, it still needs to be possible to uninstall those.

So as I said, we need to improve the relationship tracking of package extensions instead of just treating it as a glorified collection.  Not just for languages, everything that uses the package type.  This way a developer can toggle via the API whether an individual extension installed as part of a package can be uninstalled separately or if removal requires the full package to be uninstalled (which the current code does for language extensions).

**Comment by Bakual** [comment]
I knew where it comes from, but still never understood it :smile: 

> The issue there is a legitimate one

Yes, but it was fixed the wrong way. Because currently when you accidentally delete the language files, you can't reinstall the language from the manager since Joomla thinks it still is installed. You also can't uninstall it since the package manifest is missing.
A better fix would be to allow installing languages even if they are already installed. In the manager, you could mark them as installed, but still offer to (re)install.

**Comment by infograf768** [comment]
Folks, any solution you code correctly is fine for me.
At the time, nobody objected to the solution proposed.

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/12977 is step one at trying to fix some of the relationship tracking.

Don't close this issue, that PR on its own doesn't address things to completion.

**Comment by brianteeman** [comment]
So long and farewell

**Comment by helgator** [comment]
> So long and farewell

How do we take that? No fix in the making? I guess, since the same problem is still alive and kicking 4 years later.

**Comment by zero-24** [comment]
> How do we take that? No fix in the making? I guess, since the same problem is still alive and kicking 4 years later.

Well that issue was closed in 2016 when this is still an issue please open a new issue with the steps to reproduce it now so we can keep track of that. Thanks.

**Comment by brianteeman** [comment]
it is still an issue

**Comment by helgator** [comment]
Well that is the problem - it is not reproducible, it just happens every now and then to arbitrary languages.

**Comment by Bakual** [comment]
Afaik you can now at least reinstall the language pack and then properly uninstall it. At the time of this issue, this wasn't possible.
