### ISSUE TITLE
Lastvisit timestamp ignored timezone

### ISSUE THREAD

**Issue by Flocke28** [joomla/joomla-cms#14284]
### Steps to reproduce the issue
Rigister timestamp used timezone settings but not lastvisit timestamp. On new member lastvisit timestamp is in the past before registred.

**Comment by franz-wohlkoenig** [comment]
Can you please give System Information like Joomla-Version, ...?

**Comment by Flocke28** [comment]
Joomla: 3.6.5 
Timezone: Berlin
Shared Webhosting via 1&1

**Comment by franz-wohlkoenig** [comment]
Issue is solved, tested on 3.7.0-rc1

**Comment by Flocke28** [comment]
Issue isn't fixed in Joomla 3.7. 

Register Date is 2 hours in the future. Timezone Settings in Joomla config = "Berlin". Last visit timestamp is correct. Now the register timestamp ignore the timezone settings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14284">issues.joomla.org/tracker/joomla-cms/14284</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@Flocke28 can you please retest on latest Staging? There was in the last Weeks a PR for Timezone-issue, can't find now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14284">issues.joomla.org/tracker/joomla-cms/14284</a>.</sub>

**Comment by Flocke28** [comment]
Nope. Issue is still present. 

Server Time : 20:45 h

Register time: 22:45 h
Last Visit time: 20:45 h

Global Settings: time zone: Berlin

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14284">issues.joomla.org/tracker/joomla-cms/14284</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Can't confirm. 

Set timezone on "Berlin". Add new User (has only Registration Date). Login and -out this User got correct Date and Time.
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ghost** [comment]
If this PR get no Response, it will be closed at 17th September 2017.

**Comment by Flocke28** [comment]
Please close the Thread. 

I tought the User was added my Joomla but Chronoforms use a own script. i changed a line in chronoforms and now the timestamp is correct.

Sorry
