### ISSUE TITLE
Profile plugin fields can be left empty when required on admin edit

### ISSUE THREAD

**Issue by blanderson22** [joomla/joomla-cms#14805]
### Steps to reproduce the issue
Enable profile plugin. set fields to required for site and admin edit. We used Phone, Company, and website in our test.

### Expected result
Profile plugin fields are required during admin edit.

### Actual result
Can save profile during admin edit while profile plugin fields are empty.

### System information (as much as possible)
Joomla 3.6.5

**Comment by Fedik** [comment]
I can confirm, it is broken in 3.6.5, but works fine in 3.7(dev)

**Comment by franz-wohlkoenig** [comment]
In 3.6.5 and 3.7-staging (nightly build): 

- Set "Phone" as "Required" on "registration and administrator user forms" and "User profile fields for profile edit form" 
- let "Phone" empty
- user Profile is saved.

**Comment by zero-24** [comment]
See: https://docs.joomla.org/J3.x:Update_from_3.6.x_to_3.6.5_Profile_fields altest this should fix the frontend error

**Comment by franz-wohlkoenig** [comment]
thanks for Info, @zero-24, should i  open a new Issue about same Behaviour in 3.7?

**Comment by zero-24** [comment]
If this is still a issue in 3.7 the FAQ thing i linked is not the right fix. Maybe @blanderson22 can confirm if that fixes the problem or not?

**Comment by franz-wohlkoenig** [comment]
@zero-24 tested on 3.6.5 and 3.7: FAQ thing linked doesn't fix Problem.

**Comment by Fedik** [comment]
Last time when I tried to debug this thing, the problem was that `onContentPrepareForm` called twice in some reason

**Comment by Fedik** [comment]
hm, I just tested on the Staging branch, and all works fine, I cannot save an empty value in a required field

**Comment by franz-wohlkoenig** [comment]
Field "Phone" is set required:
![bildschirmfoto 2017-04-03 um 20 08 16](https://cloud.githubusercontent.com/assets/8235763/24623630/59824fde-18a9-11e7-863a-5d7b11eb5b11.JPG)

**Comment by Fedik** [comment]
@franz-wohlkoenig ah you about the backend, I tested frontend only 😄

**Comment by ghost** [comment]
closed as having Pull Request #19141
