### ISSUE TITLE
after updating 3.7 error

### ISSUE THREAD

**Issue by lupino2b** [joomla/joomla-cms#15616]
### Steps to reproduce the issue

Trying to import .csv into k2 with csvi pro
I get this error this componnet work fine in joomla 3.6.5. 

### Expected result

Fatal error: Class 'JComponentRecord' not found in /homepages/19/d671764298/htdocs/libraries/joomla/database/driver/mysqli.php on line 886

### System information (as much as possible)
PHP exécuté sur 	Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Version de la base de données 	5.5.54-0+deb7u2-log
Interclassement de la base de données 	utf8_general_ci
Collation de la connexion à la base de données 	utf8mb4_general_ci
Version de PHP 	7.1.4
Serveur web 	Apache
Serveur web pour interface PHP 	cgi-fcgi
Version de Joomla 	Joomla! 3.7.0 Stable [ Amani ] 25-April-2017 15:36 GMT
Version de la plateforme Joomla! 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navigateur 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by tonypartridge** [comment]
Hello,

K2 haven't tested and are advising ALL users not to use Joomla! 3.7 with the current version of K2.

**Comment by lupino2b** [comment]
puis je downgrader en 3.6.5 mon installation de joomla ?

**Comment by tonypartridge** [comment]
Or restore from the backup you took prior to updating.

**Comment by lupino2b** [comment]
I have restore my site from a backup. Thank you for your time cordially.

**Comment by fevangelou** [comment]
@tonypartridge First off, who said K2 hasn't been tested with Joomla 3.7? Secondly, I tweeted that folks should not upgrade to J3.7 because **JOOMLA** has a bug with the calendar fields when called via JHtml, it is NOT a bug in K2 (and that's why it was subsequently fixed in J). Furthermore, the issue above does not mention any K2 files or path. Even the class "JComponentRecord" is nowhere to be found in K2's files.

So this is indeed probably a bug somewhere in Joomla or in CSVi Pro. K2 has NOTHING to do with this.

**Comment by babatic** [comment]
I got the same problem. When i tryto downgrade to joomla 3.6.5, the problem is still there. Help please. My website is https://www.babatic.be/ .

**Comment by tonypartridge** [comment]
Hello,

Please enable maximum error reporting and joomla debug mode their please

**Comment by babatic** [comment]
public $debug = '1';
	public $debug_lang = '1';
	public $error_reporting = 'default';

**Comment by brianteeman** [comment]
The forum is the best place for support https://forum.joomla.org
