### ISSUE TITLE
Mobile views: modals created by xtd plugins show only partially

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#18447]
For mobiles view < 800x 600 (same for 728 x 1024), the xtd plugins modals (article, menu, contact, image, field) are cut off and there is no way to close their display.

Example here for 600 x800 and xtd-article 
![screen shot 2017-10-30 at 11 24 32](https://user-images.githubusercontent.com/869724/32166027-f2a8fd2e-bd64-11e7-812a-513a413d4249.png)
(it is worse at smaller sizes)

Tested with Firefox View Responsive Layouts tool.

**Comment by dgrammatiko** [comment]
@infograf768 is this a tinyMCE triggered modal?

**Comment by infograf768** [comment]
My tests indeed were done with TinyMCE. If I use Codemirror the modal adapts itself to the window and displays a close button 
![screen shot 2017-10-30 at 11 44 12](https://user-images.githubusercontent.com/869724/32166930-a7384ea0-bd67-11e7-98d7-4f9812c061d3.png)

EDIT: we lose the Search Filters in CodeMirror

**Comment by dgrammatiko** [comment]
> we lose the Search Filters in CodeMirror

It's designed that way, the button hides in smaller screens

Pretty sure I've fixed it in J4 for media field: https://github.com/joomla/joomla-cms/blob/f34dac1f55d9e740d7dd022fd7ad0af37e991f20/media/editors/tinymce/js/plugins/media/media.js#L13-L14

Not so sure that we can apply this in J3 (we're still got mootools for those buttons :( )

**Comment by C-Lodder** [comment]
TinyMCE use JS to apply a fixed width to the modal.

In J4, the modal doesn't overlap, but instead is a small box which simply isn't big enough.

**Comment by dgrammatiko** [comment]
@C-Lodder there is a PR for that: https://github.com/joomla/joomla-cms/pull/17906

**Comment by infograf768** [comment]
@dgt41 
https://github.com/joomla/joomla-cms/pull/17906 does not solve the issue here.

**Comment by dgrammatiko** [comment]
Is this J3 or J4 issue?

**Comment by Quy** [comment]
@dgt41 Judging from the screenshots, it appears to be J3.

**Comment by infograf768** [comment]
J3 indeed

**Comment by dgrammatiko** [comment]
This one might be tricky to patch, I’ll try some idea later on today

**Comment by ghost** [comment]
@dgt41 any Progress on this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18447">issues.joomla.org/tracker/joomla-cms/18447</a>.</sub>

**Comment by twister65** [comment]
If you replace : 
https://github.com/joomla/joomla-cms/blob/78deef82518f86c1c08f59ed2ddfe5fac327cfcf/plugins/editors/tinymce/tinymce.php#L818
By : 
`$tempConstructor[] = 'modalOptions.width="auto";';`

the xtd plugins modals (article, menu, contact, image, field) are responsive.
See https://github.com/joomla/joomla-cms/issues/20350#issuecomment-419123123

**Comment by twister65** [comment]
When you click any button on the TinyMCE toolbar, all popup (modal) windows are not responsive.
To avoid this problem, you need to put your xtd buttons below the editor like other editors (CodeMirror, JCE, ...), I fixed it by calling displayButtons instead of tinyButtons : 
https://github.com/twister65/joomla-cms/blob/xtd-btns/plugins/editors/tinymce/tinymce.php

**Comment by mbabker** [comment]
> To avoid this problem, you need to put your xtd buttons below the editor like other editors (CodeMirror, JCE, ...), I fixed it by calling displayButtons instead of tinyButtons

That's not happening.  It was a deliberate decision to integrate the extended buttons (xtd plugin group) into TinyMCE as "native" buttons instead of the disconnected buttons below the editor.

**Comment by twister65** [comment]
TinyMCE 5 incoming, which is responsive: https://www.tiny.cloud/developer-preview/
Adaptive mobile and tablet support.

> We rewrote TinyMCE's UI components (toolbars, menus, buttons, etc) to use CSS Flexbox, SVG, and other modern technologies.

**Comment by C-Lodder** [comment]
@twister65 Can't be used in J3 as it doesn't support IE8

**Comment by twister65** [comment]
I am disappointed about this:
> Since TinyMCE version 4.6.0 Internet Explorer 8-10 is not supported, if you need legacy browser support, the 4.5.X branch is maintained with critical fixes.
https://www.tiny.cloud/docs-preview/general-configuration-guide/system-requirements/#browsercompatibility

**Comment by twister65** [comment]
I'm embarrassed, because if I take a picture, and want to add it to my site with my phone, then I can not.
I guess a lot of people have to be in that same situation.
We can not change an article when we are traveling (vacation, business trip, ...).

**Comment by twister65** [comment]
That's why this issue interests me because I already had it.
Does anyone have a solution ?
Can not we adapt the tinyMCE source code for Joomla ?

**Comment by mbabker** [comment]
We're not forking the editor to be able to upgrade it and retain IE8 support.  How TinyMCE support looks in J4 (where it is using a TinyMCE 4.7 release last I was aware) is another story.

**Comment by twister65** [comment]
Perhaps, using TinyMCE in a Bootstrap Dialog.
https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog
Look at this example, the modal seems to be responsive : 
http://fiddle.tinymce.com/oxdaab

**Comment by dgrammatiko** [comment]
@twister65 in a Bootstrap Dialog? Really? What will be the benefit of hiding the editor and then force a user to open a modal to interact with the editor? I will not even bother to comment on the Bootstrap Dialog...

Not to mention that your proposal is not fixing something:
<img width="500" alt="screenshot 2018-11-14 at 23 40 48" src="https://user-images.githubusercontent.com/3889375/48517510-d1dc8b00-e866-11e8-87f2-7d2bf479ca18.png">

**Comment by twister65** [comment]
IE8 ? Really? Who still uses such a browser ?
https://www.w3schools.com/browsers/browsers_explorer.asp
http://gs.statcounter.com/browser-version-market-share

I can't see it in the Joomla v3.x requirements : 
https://downloads.joomla.org/technical-requirements

**Comment by C-Lodder** [comment]
@twister65 https://docs.joomla.org/Joomla_Browser_Support

That applies to J3, not J4

**Comment by twister65** [comment]
@C-Lodder and Netscape ;-)
Have you seen the statistics ? Less than 0.2% for old IEs.
When we log in as an administrator in Joomla, we have a php warning:

> Warning
Your PHP version, 5.6.34, is only receiving security fixes from the PHP project at this time. This means your PHP version will soon no longer be supported. We recommend planning to upgrade to a newer PHP version before it reaches end of support on 2018-12-31. Joomla will be faster and more secure if you upgrade to a newer PHP version. Please contact your host for upgrade instructions.

Despite the requirements of Joomla:

> PHP | 5.6 or 7.0 + (Recommended) | 5.3.10 (Minimum).

Why not for browsers ?

**Comment by twister65** [comment]
> Support for older versions of Internet Explorer ended.
Beginning January 12, 2016, only the most current version of Internet Explorer available for a supported operating system will receive technical supports and security updates.

https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

**Comment by C-Lodder** [comment]
@twister65 Yes I'm aware of the stats. The fact being is that Joomla must continue support for IE8 in the 3.x series as it's follows sematic versioning. Dropping support for a major browser version such as IE8 will require a major Joomla updates, thus Joomla 4.

PHP versions are completely different from browser versions and are not related in the slightest.

Let's take a handful of sites, for example 1 million, that are running Joomla on PHP 5.3 and 500k of those users have other websites using perhaps a custom framework, cms, etc etc that was written for PHP 5.3. Let's then say that Joomla decided to stop supporting PHP 5.3 in 3.10. Those 1 millions websites then get updated from Joomla 3.9 to 3.10 the day it's released (wouldn't that be lovely). Those 1 million users then notice errors being thrown all over the place on their sites. They then notice they have to update their PHP version to 7.x and proceed to doing so.
The other 500k users that have other PHP 5.3 applications on their servers then notice errors and find they don't have the time, money, or resources to migrate what could potentially be a huge system.
Times that scale by 10 and you'll most likely have each company voting for JEXIT

Besides, the message you see is purely a warning. Joomla 3 still supports PHP 5.3.10 and will not break that. **Recommended** and **minimum** requires are again, 2 very different things.

**Comment by twister65** [comment]
You can close this issue. See PR #23091.

**Comment by infograf768** [comment]
Closing.
