### ISSUE TITLE
[4.0] Smart Search Indexer don't work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#18861]
### Steps to reproduce the issue
Starting Smart Search Indexer doesn't make any Progress in Modale-Window.
### System information
4.0.0-dev
Multilanguage Site (4 Lang.) & Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by C-Lodder** [comment]
Do you get any console log errors?

**Comment by ghost** [comment]
Yes:

![bildschirmfoto 2017-11-28 um 07 32 51](https://user-images.githubusercontent.com/8235763/33305429-5fc64a6e-d40e-11e7-8d4d-3b5522a26fb7.jpg)

**Comment by ghost** [comment]
closed as having Pull Request #18959

**Comment by wilsonge** [comment]
Is this definitely fixed by #18959 - that just seems to be removing jQuery from the javascript code - I can't see how it fixes that the server is giving back invalid JSON?

**Comment by ghost** [comment]
Test #18959 was successfully @wilsonge.

**Comment by C-Lodder** [comment]
@wilsonge yes it does seem odd that the rewrite fixed this issue, however lets leave it be and it the issue arises again, this can be reopened

**Comment by infograf768** [comment]
The issue is still present here.
See https://github.com/joomla/joomla-cms/pull/18959#issuecomment-350649693

**Comment by ghost** [comment]
@infograf768 can you please retest cause on my Side this Issue is solved.

**Comment by kbgorman** [comment]
I am having this issue in Joomla! 3.8.6	- any advice on what to do would be appreciated. ![screen shot 2018-04-01 at 11 44 10](https://issues.joomla.org/uploads/1/c24d5d833ba2ce89d34419524e5ae1ee.jpg)

Thanks, Kathy<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18861">issues.joomla.org/tracker/joomla-cms/18861</a>.</sub>

**Comment by ghost** [comment]
@kbgorman this Issue is about 4.0. Please ask help on the [forums](https://forum.joomla.org/). This repository concerns in first Place Joomla-Core coding.

**Comment by kbgorman** [comment]
Thank you for your help,  I’m sorry, I should have noticed  -  I’ll check in the other forum.

Kathy

**Comment by ggppdk** [comment]
@kbgorman 

what you posted is the failure the JSON error to parse the responce text which is not useful

**Go to network TAB** and you look **at the actual response text**

probably you have some 3rd party extension printing a PHP notice because you have enabled "error_reporting" in Joomla Global configuration,
then post it to Joomla forums or report to the author of the plugin

**Comment by kbgorman** [comment]
Thank you for your response . I’m sorry I posted in the wrong forum but you’ve given me some where to go with this. It’s very helpful. Thank you!

Kathy

**Comment by Quy** [comment]
Closing as not reproducible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18861">issues.joomla.org/tracker/joomla-cms/18861</a>.</sub>
