### ISSUE TITLE
[4.0] Navigating between 'System' items no longer possible with 1 click

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#26409]
### Steps to reproduce the issue
Since moving certain items to a **Systems** menu item, we are no longer able to navigate directly between these items. For example in J3 we can navigate directly from **Templates** to **Template Styles**
or from **Languages** to **Language Overrides** via the top menu. 

In Joomla 4 this is no longer posible. We must click back in to the **System** menu item first.

**Comment by Scrabble96** [comment]
This is similar to the issue I posted at #25916

**Comment by Quy** [comment]
Duplicate #24497.

**Comment by N6REJ** [comment]
dont' get me started on ui design for j4

**Comment by infograf768** [comment]
Using the alternate preset for the admin menu makes it easier.

**Comment by ciar4n** [comment]
Maybe this 'alternate preset' should be made the default?

**Comment by N6REJ** [comment]
the who what where?????

**Comment by SharkyKZ** [comment]
@N6REJ See `Choose Preset` option in administrator menu module.

**Comment by Quy** [comment]
Duplicate #24497.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26409">issues.joomla.org/tracker/joomla-cms/26409</a>.</sub>

**Comment by ciar4n** [comment]
#24497 has no description. How is this a duplicate?

**Comment by brianteeman** [comment]
It also was referring to removing the sidebars that existed in components. This is a different and valid issue

**Comment by PhocaCz** [comment]
@ciar4n 

A possible solution regarding missing top menu is to use the administration module.

Atum includes "customtop" position and it is possible to use "Preset - Alternative Main Menu" preset.

![admin module](https://i.imgur.com/XEa5gt7.png)

So, Joomla! 4 is ready for top menu:
![top menu](https://i.imgur.com/MvBDIlm.png)

(this is a screenshot of a module built on a solution from Clifford E Ford - https://github.com/ceford/j4xdemos-admin-mod-topmenu )

**Comment by infograf768** [comment]
@PhocaCz 
Does this work OK in RTL? Asking as I see the `+` on the wrong side in LTR

**Comment by ciar4n** [comment]
The vast majority of users will neither load a preset or install a 3pd extension. I think a solution to this is best applied to the default menu.

**Comment by ReLater** [comment]
I've never understood why the easy-to-use sidebar codes of J3 have been removed completely from J4 instead of putting the component specific sidebar menu items in a dropdown (whereever positioned). Would have been less work at the end of the day (also for 3rd developers).

**Comment by PhocaCz** [comment]
> @PhocaCz
> Does this work OK in RTL? Asking as I see the `+` on the wrong side in LTR

The original solution is built on the external Smartmenus library, so I don't know. I am currently testing and modifying it - to run based only on Boostrap (with click or hover event) and it seems, with small solvable design issues (plus icons, etc.) it can be even used in RTL:

![rtl](https://i.imgur.com/OsKSvzS.png)

Changing position of plus icon is just a question of small corrections in html and css:

![plus](https://i.imgur.com/xQ6VTjO.png)

**Comment by PhocaCz** [comment]
@ReLater 
@ciar4n 

For me personally, using external extension is more advantageous, I do not have to participate in discussions and explain that thanks to the top menu when working on desktop I am about 3276 light-years faster in system administration than with the side menu with missing items. :-)

What is great about Joomla! 4, it is ready to extend the menu options. 

So it's just a matter of time and users. If a lot of users demand a top menu, it will have to be addressed in the core. If not, then there will be a possibility of using extension for those few individuals.

**Comment by dgrammatiko** [comment]
Couple of thoughts here as I'm the one who proposed this new (weird)menu:
- The approach is the same as in all the operating systems (IOS, Android, Windows, MacOS, Linux, etc). You have direct access to all the daily tasks but for anything that is system related you have a control panel. I do understand that Joomla users are very attached to the old system thus the frustration but if you think about it this makes sense. You **won't** enable/disable/add/remove/tweek extensions/plugins/templates in a daily basis. Actually these are tasks only for the administrators/designers not the people who will enter data or publish/unpubish content!
- Shall the Alternative menu be the default? Probably yes, as the one who will install Joomla and set it up is the administrator. But maybe (I don't know if that is even possible) it can be done through the permissions/groups, eg administrator gets the alternative, anyone else with access to the backend gets the new system...

**Comment by PhocaCz** [comment]
@dgrammatiko 

I understand the concept of the side menu. I personally withdraw from this discussion because I have found the optimal solution for me (external extension). The question for the core team in the future is to find out what Joomla! system administrators want. If the side menu suits them or they would like to have the option of a top menu. What about not having active menu items displayed, etc. But this is a question for the future and a question for research.

As written in other posts, I still see issues:
- when there is no active menu item displayed
- when there are two side menus

![menu](https://i.imgur.com/0p15YW5.png)

**Comment by ciar4n** [comment]
@PhocaCz This discussion is not about a top vs side menu. Nor is it the place to promote your own extensions.

**Comment by dgrammatiko** [comment]
> I understand the concept of the side menu.

@PhocaCz I'm not talking about the side menu, I'm answering the question raised in this PR about not having direct access to some menus. You're talking to something totally unrelated with this discussion and FWIW the side menu was not something I was involved but I support the idea as all the rest CMS' out there have also this layout... If you want to raise that discussion please open another issue

**Comment by PhocaCz** [comment]
> @PhocaCz This discussion is not about a top vs side menu. Nor is it the place to promote your own extensions.

Please, don't attack me in person, I don't promote any of my extension, such extension does not exist. I described extension made by Clifford E Ford. Possible solution for all the problems described here.

( https://github.com/ceford/j4xdemos-admin-mod-topmenu )

https://github.com/joomla/joomla-cms/issues/26409#issuecomment-620798581

**Comment by PhocaCz** [comment]
@dgrammatiko - Ok, sorry for misunderstanding.

**Comment by dgrammatiko** [comment]
Just for reference there were quite some discussions on this topic already, so if anyone wants to figure out the why's they could start digging from here: https://github.com/joomla/joomla-cms/pull/15660

**Comment by ciar4n** [comment]
I largely agree with the new J4 menu format. I just believe some commonly used items have become harder to navigate. I admit thou that what I consider 'commonly used' is very much subjective without any user data.

@PhocaCz My apologies, I didnt mean to insult.

**Comment by brianteeman** [comment]
> I admit thou that what I consider 'commonly used' is very much subjective without any user data.

90% of users only use 10% of the features but they all use a different 10%
and this is why I pushed for years for the ability to create our admin menus so that each user gets to see their own 10%

**Comment by ReLater** [comment]
@PhocaCz 

Just to clarify my https://github.com/joomla/joomla-cms/issues/26409#issuecomment-621104382 because you answered https://github.com/joomla/joomla-cms/issues/26409#issuecomment-621140313

I was talking about the Joomla 3 sidebar, e.g. menu items "Templates", "Styles" when I open a com_templates view.
The codes that provide these menu items and populate a list have been removed from Joomla 4.
Where to position these quick links menu items then and how is another question (top, left, right, whatever) but it's to late now because the decision was made to remove all the logic.

I relied on this comment: https://github.com/joomla/joomla-cms/issues/24742#issuecomment-487364342 but the JHtml helper methods have also been removed meanwhile.

**Comment by PhocaCz** [comment]
> I was talking about the Joomla 3 sidebar, e.g. menu items "Templates", "Styles" when I open a com_templates view.
> The codes that provide these menu items and populate a list have been removed from Joomla 4.
> Where to position these quick links menu items then and how is another question (top, left, right, whatever) but it's to late now because the decision was made to remove all the logic.

Yes, I understand, my comment was not about somehow replacing the Joomla! 3 sidebar menu but only to give information that there is some alternative - at least in one case. In Joomla! 3, there were two options: 
a) switch by sidebar menu (removed in J!4)
b) switch by top menu (removed in J!4)

So if there is no way with a) at least there is b) possible.

BTW: "Joomla! 3 sidebar" menu still exists in J!4:

![Joomla! 3 sidebar menu in Joomla! 4](https://i.imgur.com/NKVioTX.png)

**Comment by brianteeman** [comment]
@wilsonge I guess you need to make a decision here

**Comment by wilsonge** [comment]
Don't think so. It's shipped and largely in people's muscle memories at this point
