### ISSUE TITLE
Dashboard error after update Joomla ‎4.0.0-alpha12 to 4.0.0-beta1-dev.

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#27598]
### Steps to reproduce the issue
Update Joomla using Joomla update using custom update path : https://update.joomla.org/core/nightlies/next_major_list.xml with Write file directly option.
After the update process finished, when I access the dashboard, th layout is broken and returned error message : 'Joomla\Module\LatestActions\Administrator\Helper\LatestActionsHelper' not found

![image](https://user-images.githubusercontent.com/4277547/72888836-f4a6e100-3d40-11ea-8f78-5ba601b1220c.png)
### Expected result

Dashboard working properly

### System information (as much as possible)

Joomla ‎4.0.0-beta1-dev

PHP 7.3.11
mysql 8.0.18

**Comment by alikon** [comment]
update from alpha  are still not supported

**Comment by mbabker** [comment]
I still think that’s a BS policy as right now you are basically telling people to not test J4 as a real website and only use it as a test bed for new features.  Maybe one day this project will actually get serious about supporting proper end-to-end development workflows and not telling people to get bent for answering the call to testing.

This may damn well be a legitimate update issue in the 4.0 code.  Is it going to be blown off until you release 4.0.1?

**Comment by alikon** [comment]
as long  we  are still in alpha.... shouldn't seems to me a big problem,
anyway,  you know that we are very few that shake they hand in the dust, so i've just informed what it is available right now... surely i agree with you that this problem should be resolved as soon as possibile, anyway, we have had  the same issue on the 1.x/2.x./3.x

**Comment by SharkyKZ** [comment]
This will be an issue updating stable versions if not fixed. It's caused by namespace map not being re-generated when updating Joomla.

**Comment by wilsonge** [comment]
We should probably always delete that file on upgrade in the script. We already have the plugin doing it on every extension install.

**Comment by brianteeman** [comment]
Is it enough to just add this to the namespacemap plugin
```

	/**
	 * Update / Create map on Joomla update
	 *
	 * @param   JInstaller  $installer  Installer instance
	 *
	 * @return  void
	 *
	 * @since   4.0.0
	 */
	public function onJoomlaAfterUpdate()
	{
		// Update / Create new map
		$this->fileCreator->create();
	}

```

**Comment by wilsonge** [comment]
I’m not at a computer now to check - but I’m not aware of an event like that. I think we’d need to trash the file like we do in the plugin but direct in script.php

**Comment by brianteeman** [comment]
@wilsonge I didnt invent it - it already exists ;)

Enjoy the game

**Comment by alikon** [comment]
maybe a simple & silly solution can be adding
```php
$recreate = new JNamespacePsr4Map;
$recreate ->create();

```

after https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/script.php#L105

**Comment by Quy** [comment]
It is a different error now with the latest dev.

> An error has occurred.
500 Unknown column 'fp.featured_up' in 'field list' 
```
Call stack
--
# | Function | Location
1 | () | JROOT\administrator\modules\mod_popular\src\Helper\PopularHelper.php:82
2 | Joomla\Module\Popular\Administrator\Helper\PopularHelper::getList() | JROOT\administrator\modules\mod_popular\mod_popular.php:16
3 | include() | JROOT\libraries\src\Dispatcher\ModuleDispatcher.php:54
4 | Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\ModuleDispatcher.php:57
5 | Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch() | JROOT\libraries\src\Helper\ModuleHelper.php:300
6 | Joomla\CMS\Helper\ModuleHelper::renderRawModule() | JROOT\libraries\src\Helper\ModuleHelper.php:173
7 | Joomla\CMS\Helper\ModuleHelper::renderModule() | JROOT\administrator\components\com_cpanel\tmpl\cpanel\default.php:61
8 | include() | JROOT\libraries\src\MVC\View\HtmlView.php:387
9 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT\libraries\src\MVC\View\HtmlView.php:192
10 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT\administrator\components\com_cpanel\src\View\Cpanel\HtmlView.php:155
11 | Joomla\Component\Cpanel\Administrator\View\Cpanel\HtmlView->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:691
12 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\administrator\components\com_cpanel\src\Controller\DisplayController.php:54
13 | Joomla\Component\Cpanel\Administrator\Controller\DisplayController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:729
14 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
15 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:384
16 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:131
17 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:174
18 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:231
19 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
20 | require_once() | JROOT\administrator\index.php:36
```

**Comment by Quy** [comment]
Closing as the reported issue is no longer reproducible. See #29841 instead.
