### ISSUE TITLE
[4.0] Medium Screen width in backend template

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#28799]
### Steps to reproduce the issue
On my 13,5'' laptop the backend looks like this: 

![screen-width](https://user-images.githubusercontent.com/1035262/80281928-d6b99580-870e-11ea-8b75-5c24895a0a46.JPG)

It is a problem when there are too many tabs. There was a solution where the tab area hat it's own scrollbar but this has disappeared. 

### Expected result
Complete screen, Top and toolbar have 100%, no horizontal scrolling needed

### Actual result
see screen

**Comment by infograf768** [comment]
Confirmed

**Comment by faustonenci** [comment]
Confirmed

**Comment by adj9** [comment]
I confirm this position anomaly. I'm on Safari 13.0.5 and I have a 15 '' retina screen.
<img width="1428" alt="Schermata 2020-04-25 alle 17 26 56" src="https://user-images.githubusercontent.com/5918444/80283709-10dc6480-871a-11ea-975c-1358664279f2.png">

**Comment by brianteeman** [comment]
The physical dimensions of the screen dont really help to resolve this. Can you please post the screen resolution, browser and operating system

**Comment by infograf768** [comment]
Macintosh, whatever the screen resolution, whatever the browser...

**Comment by chmst** [comment]
Win 10, Surface book, every resolution(I use 3000x2000). FF, Edge and chrome

**Comment by PhilETaylor** [comment]
![Screen Recording 2020-06-16 at 10 37 PM](https://user-images.githubusercontent.com/400092/84831153-bb8a4880-b022-11ea-859e-7055b87ba787.gif)


even a 27" iMac scaled to 1600px x 1600px viewport size I get the same thing. 

https://www.webfx.com/tools/whats-my-browser-size/ reports my viewport at 1600px x 1600px ! 


> Macintosh, whatever the screen resolution, whatever the browser...

I agree. 

This has to be a release blocker @wilsonge  ??

**Comment by wilsonge** [comment]
yeah it is. marked as such.  can reproduce on my laptop too btw

**Comment by SharkyKZ** [comment]
Was horizontal scrolling removed intentionally? If not, why don't we just remove these terrible overrides?

**Comment by infograf768** [comment]
Time to reconsider the use of uitab? https://github.com/joomla/joomla-cms/issues/29580#issuecomment-643653990

**Comment by PhilETaylor** [comment]
Another example, On a SSL Site, Editing a user 1600px x 1600px (Half a 27 inch iMac retina screen) 

<img width="1619" alt="Screenshot 2020-06-22 at 18 56 03" src="https://user-images.githubusercontent.com/400092/85319932-34bdeb80-b4ba-11ea-85bf-50e2daeca32d.png">

This one can be slimmed down a lot if the Tabs were: 

 - Account
 - User Groups
 - Settings
 - Accessibility
- Log Options
 - Webauthn
 - API
 - 2FA or Two Factor Auth

But still probably too wide for most screen resolutions.

**Comment by brianteeman** [comment]
This was resolved with the horizontal scroll but someone removed it.

**Comment by PhilETaylor** [comment]
but is horizontal scrolling any better? I dont know many other websites that I can horizontal scroll on ...

**Comment by richard67** [comment]
For the tabs there is a PR which solves it by wrapping the tabs into rows if too many.

Please test PR #30675 and report back there if you like the solution or not.

@chmst Will that PR solve this issue here completely? Or is something remaining to be fixed?

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/pull/30675#issuecomment-694844794

**Comment by richard67** [comment]
@chmst The question if some issues are remaining with that PR is still not answered.

**Comment by chmst** [comment]
The issue is solved, thank you.

**Comment by wilsonge** [comment]
For me in some views (e.g. com_users) the toolbar also extends off the edge of the screen

**Comment by richard67** [comment]
@wilsonge Shall we re-open this issue?

**Comment by richard67** [comment]
@Ruud68 Would it make sense to do the same for the toolbar as you have done for the tabs with PR #30675 , so the toolbar wraps, too?

**Comment by Ruud68** [comment]
I have no clue what @wilsonge is referring to, so can't reproduce = can't fix.
btw while this was labeled 'release blocker', these should be labeled release blocker as well: #29706 and #29710  test users for my extensions are reporting these to me as unusable UX and 'must fix'
