### ISSUE TITLE
J-Admin: Warning! Internet Explorer should not be used for proper operation of the Administrator Backend.

### ISSUE THREAD

**Issue by kyavuz54** [joomla/joomla-cms#37409]
### Problem identified
I'm getting "Warning! Internet Explorer should not be used for proper operation of the Administrator Backend." on Joomla 4.0.6 while I'm on Chrome. Frontend works just fine.
![image](https://user-images.githubusercontent.com/102620666/160682020-769e7e4f-d205-4173-ae0d-48976325d5e2.png)

### Proposed solution
I renamed .htaccess to htaccess.txt, but it didn't help.

### Open questions
Any idea?

**Comment by drmenzelit** [comment]
Internet Explorer is dead, it should not be used for anything... Please use modern browsers like Firefox, Chrome, Edge, Brave, Vivaldi....

**Comment by richard67** [comment]
Hmm, it looks as if there is no js and css loaded at all, and so that message about IE is not hidden like it should be. Please make sure to comment out the last section in your .htaccess file which is about using precomptessed js and css.

**Comment by brianteeman** [comment]
@drmenzelit as the user stated they are using chrome and the screenshot is chrome

The confusion is because when javascript and css etc does not load then you can see that message.

The screenshot does however explain exactly what the error is.  which is what @richard67 said (while I was searching the docs site to try and find the detailed explanation)

**Comment by richard67** [comment]
Not related to the issue, but you should update to the current version 4.1.1 as soon as this problem is fixed because your 4.0.6 is old and has security issues. There is nothing special with updating to 4.1.1, it is a normal update within the same major version, not such a big thing like a 3.10.x to 4.y.z update.

**Comment by kyavuz54** [comment]
Yes, I'm on Chrome. 

I did the suggested, so the bottom part of .htaccess went from this
![image](https://user-images.githubusercontent.com/102620666/160693905-9d798330-9d45-4cd7-b07f-9fe0e31a8a80.png)

to this
![image](https://user-images.githubusercontent.com/102620666/160693955-b6665466-14fb-42b5-bd75-d55fde305195.png)
 
But, I still see the following 
![image](https://user-images.githubusercontent.com/102620666/160694176-63ac289b-791b-401e-b931-54c3c8aebee2.png)

That is the plan to update if I can get this to work. 

Any more ideas?

**Comment by Hackwar** [comment]
You have this only in the administrator? Not in the frontend? Do you maybe have an (outdated version of) Akeeba Admintools installed? Regardless, your browser can't load any JS/CSS, so you would have to find out why that is. It is not an issue of core Joomla. A hosting issue, a third party extension or a misconfiguration in htaccess somewhere...

**Comment by Hackwar** [comment]
I would assume that somehow you are encoding your content with gzip twice.

**Comment by kyavuz54** [comment]
This happens only in the admin, not in the frontend. 
Akeeba Admin Tools Core version is 7.1.1.

I don't see any other gzip related coding on .htaccess besides the ones that I commented out

I'll have to get in touch with the hosting.

**Comment by richard67** [comment]
According to https://www.akeeba.com/download/admin-tools.html your version of admin tools is not the latest one.

**Comment by kyavuz54** [comment]
This is weird.

I was able to go on the admin panel on my cell phone. I updated all extensions and the Joomla to 4.1.0 (which seems to be the only available version that I see after checking for a new update).

Unfortunately, I still get the same warning on Chrome, Firefox, Opera, and Edge "Warning! Internet Explorer should not be used for proper operation of the Administrator Backend."

Why don't JS/CSS files load on regular browser?

**Comment by kyavuz54** [comment]
I restored files from a backup that is a month old. I renamed the .htaccess to htaccess.txt which brought me to the following:
![image](https://user-images.githubusercontent.com/102620666/160717690-adcf5241-0853-47b4-8322-1d7a754a6f36.png)

Seems like I'm on the right track, but not all files load accurately.

Any suggestions?

**Comment by Hackwar** [comment]
Again, sounds like you have issues with a third party extension or your hosting, not with Joomla itself. I would advise to ask in the forum if your hoster can't help you.

**Comment by kitepascal** [comment]
Whats your gzip setting in configuration.php?

public $gzip = '0';

...and all .htaccess disabled (check also subdirectories, e.g. /media) should solve your problem.

A new inkognito browser window (close all inkognito windows before) is better for testing.

**Comment by drmenzelit** [comment]
> @drmenzelit as the user stated they are using chrome and the screenshot is chrome
> 
> The confusion is because when javascript and css etc does not load then you can see that message.
> 
> The screenshot does however explain exactly what the error is. which is what @richard67 said (while I was searching the docs site to try and find the detailed explanation)

My bad, I didn't read properly

**Comment by Hackwar** [comment]
Any news, @kyavuz54? As we all said, it looks very much like a hosting issue, for example an additional htaccess in your administrator folder or some strange server configuration. I would say that this isn't a Joomla bug.

**Comment by HLeithner** [comment]
I'm closing this for now because it seems that is not a core issue, please ask in the forum for help. If you really think or found out that's core issue you can always reopen this issue.

**Comment by jweaver0312** [comment]
I would have to disagree with the belief that it is not a core issue and the people saying its a hosting issue. If it were truly to be a hosting issue, then every browser in existence would be affected, not just Chromium based among others.

I'm having the same exact issue as the original reporter, except mine affects both the backend and frontend. I'm currently working on the .htaccess file commenting out section by section to narrow down a particular section causing it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by jweaver0312** [comment]
## These directives are only enabled if the Apache mod_headers module is enabled.
## This section will check if a .gz file exists and if so will stream it
##     directly or fallback to gzip any asset on the fly
## If your site starts to look strange after enabling this, and you see
##     ERR_CONTENT_DECODING_FAILED in your browser console network tab,
##     then your server is already gzipping css and js files and you don't need this
##     block enabled in your .htaccess
<IfModule mod_headers.c>
	# Serve gzip compressed CSS files if they exist
	# and the client accepts gzip.
	RewriteCond "%{HTTP:Accept-encoding}" "gzip"
	RewriteCond "%{REQUEST_FILENAME}\.gz" -s
	RewriteRule "^(.*)\.css" "$1\.css\.gz" [QSA]

	# Serve gzip compressed JS files if they exist
	# and the client accepts gzip.
	RewriteCond "%{HTTP:Accept-encoding}" "gzip"
	RewriteCond "%{REQUEST_FILENAME}\.gz" -s
	RewriteRule "^(.*)\.js" "$1\.js\.gz" [QSA]

	# Serve correct content types, and prevent mod_deflate double gzip.
	RewriteRule "\.css\.gz$" "-" [T=text/css,E=no-gzip:1]
	RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-gzip:1]

	<FilesMatch "(\.js\.gz|\.css\.gz)$">
		# Serve correct encoding type.
		Header append Content-Encoding gzip

		# Force proxies to cache gzipped &
		# non-gzipped css/js files separately.
		Header append Vary Accept-Encoding
	</FilesMatch>
</IfModule>

Comment all this out and it'll be fine. The question then shifts to what I said prior, if it truly were a hosting issue, then every browser in existence would have this issue, but the fact of the matter is, not all browsers share in this issue, namely Safari. If the server is gzipping css and js files, then every browser in existence should inherently share the same issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by jweaver0312** [comment]
Reposting to make it look good, forgot to preview it before posting.
```
## These directives are only enabled if the Apache mod_headers module is enabled.
## This section will check if a .gz file exists and if so will stream it
##     directly or fallback to gzip any asset on the fly
## If your site starts to look strange after enabling this, and you see
##     ERR_CONTENT_DECODING_FAILED in your browser console network tab,
##     then your server is already gzipping css and js files and you don't need this
##     block enabled in your .htaccess
<IfModule mod_headers.c>
	# Serve gzip compressed CSS files if they exist
	# and the client accepts gzip.
	RewriteCond "%{HTTP:Accept-encoding}" "gzip"
	RewriteCond "%{REQUEST_FILENAME}\.gz" -s
	RewriteRule "^(.*)\.css" "$1\.css\.gz" [QSA]

	# Serve gzip compressed JS files if they exist
	# and the client accepts gzip.
	RewriteCond "%{HTTP:Accept-encoding}" "gzip"
	RewriteCond "%{REQUEST_FILENAME}\.gz" -s
	RewriteRule "^(.*)\.js" "$1\.js\.gz" [QSA]

	# Serve correct content types, and prevent mod_deflate double gzip.
	RewriteRule "\.css\.gz$" "-" [T=text/css,E=no-gzip:1]
	RewriteRule "\.js\.gz$" "-" [T=text/javascript,E=no-gzip:1]

	<FilesMatch "(\.js\.gz|\.css\.gz)$">
		# Serve correct encoding type.
		Header append Content-Encoding gzip

		# Force proxies to cache gzipped &
		# non-gzipped css/js files separately.
		Header append Vary Accept-Encoding
	</FilesMatch>
</IfModule>
```
Comment all this out and it'll be fine. The question then shifts to what I said prior, if it truly were a hosting issue, then every browser in existence would have this issue, but the fact of the matter is, not all browsers share in this issue, namely Safari. If the server is gzipping css and js files, then every browser in existence should inherently share the same issue. The question shifts to, why those browsers in specific.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by jweaver0312** [comment]
@Hackwar that seem to be a case but I tried with Joomla Gzip page compression on and off and nothing changed the behavior, only thing that helped was commenting that section of the .htaccess out.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by jweaver0312** [comment]
To original reporter: that might be a caching issue on your part where its still showing like that, on my instance, as soon as I do that to comment it out, that resolves it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by Sandra97** [comment]
I just had this issue after transferring a site from the server of my hosting company to the server of the hosting company of my client. Commenting the section of the .htaccess solved the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by brianteeman** [comment]
what was the hosting company @Sandra97 I would like to find a way to display a helpful message on screen instead of the browser console but I dont have a host I can test this with (and failed to work out how to replicate it locally)

**Comment by Sandra97** [comment]
The issue happened at GoDaddy

**Comment by Jadzia** [comment]
I am having the same issue, the code doesn't exist in the.htaccess and its the same in all browsers not just Chrome.
It's a bit hard to disable 3rd party components when you can't get in. Will post when I fix it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by pearsony** [comment]
Has a solution to this issue been posted? A client's website is still intermittently experiencing this issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by pearsony** [comment]
I'm using Joomla 4.1.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by bomkallo** [comment]
The solution is to change "gzip page compression" from enabled to disabled. It is in global configuration. Probably you're not able to access administrator area in normal way so you need to rename .htaccess or comment out last 10-30 lines or just open configuration.php and change public $gzip = TRUE;

 Depends on hosting. If there is no styles under /administrator it means gzip compression is on and must be turned off as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>

**Comment by pearsony** [comment]
Unfortunately, all of my Joomla 4.x websites gzip set to off position.
~ Scott

**Comment by jimmyxXx** [comment]
So, which one is better - to comment off the gzip block in .htaccess as in jweaver0312's post, or to turn off gzip compression in joomla server configuration?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37409">issues.joomla.org/tracker/joomla-cms/37409</a>.</sub>
