### ISSUE TITLE
Require password reset function not registering if change of password at same time in backend

### ISSUE THREAD

**Issue by Attila-SWE** [joomla/joomla-cms#40480]
### Steps to reproduce the issue
1. Edit user in backend
2. Enter new password
3. Select that user needs to reset password at next login
4. Save
5. No orange marker at user showing that password reset will be required
6. Now edit same user and reset password button is set to no and not registered as yes
7. Change only the require reset password button without changing password
8. Save
9. Now user needs to reset password at next login

### Expected result
Password should change and require password reset should be Yes if changed at same time

### Actual result
Only password is changed and require password reset is set to no.

### System information (as much as possible)
Same issue in Joomla 3.10 as in Jooma 4.x (including 4.3)

**Comment by Attila-SWE** [comment]
Could it be that the issue is because of some ordering of functions in backend code? So instead of:

1. Change password
2. Mark as "needs password reset"
3. Save

It does

1. Mark as "needs password reset"
2. Change password
3. Ah, great! Seems that the password reset is solved
5. Save with the new password and uncheck "needs password reset"

**Comment by SumCompanyInc** [comment]
i can confirm the issue persists in joomla v5.0.3 dev branch and joomla v5.0.2
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40480">issues.joomla.org/tracker/joomla-cms/40480</a>.</sub>

**Comment by jjnxpct** [comment]
I have experienced this to I think. But on J4.

**Comment by Hackwar** [comment]
I created a PR #44519. Please test this. Since we have a PR, I'm closing this one.
