### ISSUE TITLE
showon attribute does not seem to behave properly when using !

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#41120]
### Steps to reproduce the issue

As I was testing showon in the frontend for custom fields, I noticed a strange behavior when using the negation of values (!) for the condition in the backend, when multiple values are selected.

### Expected result

When using a condition such as 'field!:value1', the field the condition is applied to should not show if 'field' has value1 or a combination of values, including value1.

### Actual result

Since a picture is worth a thousand words, here is the issue.
I have a checkbox custom field, which can have value1, value2 and value3.
I have created a custom field (icon picker), which will only show if value1 is NOT selected.

![screen shot 2023-07-06 at 16 02 21](https://issues.joomla.org/uploads/1/426fef0abf5cd68de2c37a2b097702aa.png)

Now, I head to an article and try my settings.
If the checkbox has value1, the icon field won't show.

![screen shot 2023-07-06 at 16 03 47](https://issues.joomla.org/uploads/1/811270b272366aaa834694f94bd231dc.png)

If the checkbox has value2, the icon field will show. All good until now.

![screen shot 2023-07-06 at 16 04 31](https://issues.joomla.org/uploads/1/2b498daad1cad66542d0a410cbdc0a5d.png)

Now, if the checkbox has values value1 AND value2, the icon field still shows, while it should not.

![screen shot 2023-07-06 at 16 05 23](https://issues.joomla.org/uploads/1/7a3326ae8c5597cd5aa7fadeb6c2bfd5.png)

### System information (as much as possible)

Happens in Joomla 4.3 but I suspect it may have been a long-lasting issue.

### Additional comments

n/a

**Comment by brianteeman** [comment]
> When using a condition such as 'field!:value1', the field the condition is applied to should not show if 'field' has value1 or a combination of values, including value1.

what makes you have that conclusion - I did not make the same conclusion from the docs or the various pull requests.

from my reading nowhere does it say anything about "where x IN y" only "where x EQUALS y" and "where x NOT EQUAKS y"

**Comment by obuisard** [comment]
My assumption is that when a condition is set to NOT EQUAL, if the field the condition is based on has multiple values including the value set in the NOT EQUAL' condition, then the field should not show. 

The documentation only says (https://docs.joomla.org/Form_field#Showon):

> You can also use value 'does not equal' as in showon="field1!:1".
> The syntax to show the field "bar" only when "foo" is not equal to "1":

So it is just my assumption in how I think it should behave.

**Comment by brianteeman** [comment]
It looks like this was resolved with https://github.com/joomla/joomla-cms/pull/41918

**Comment by richard67** [comment]
> It looks like this was resolved with [#41918](https://github.com/joomla/joomla-cms/pull/41918)

Not sure as that PR only dealt with the validation rule for the showon attribute.

**Comment by MacJoom** [comment]
Thank you for your contribution - this Issue has been added to the issue cleanup and will be closed shortly. Please comment if you have any further input

**Comment by obuisard** [comment]
I re-checked this, the issue is still there.

If the showon attribute of a field 'B' is check!:value1,value2 for a 'check' field that can have values 1, 2 or 3,
the field B will show if 'check' has values 1 AND 3 or 2 AND 3.

For most users, this should not matter, I suppose...
