### ISSUE TITLE
[5] npm run build:css Deprecation Warning

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#41891]
### Steps to reproduce the issue

Follow the instructions to clone joomla-cms on localhost. 
Checkout: git checkout 5.0-dev
When building or rebuilding after testing, npm run build:css
I get a sequence of deprecation warnings. On a separate clone with 4.3-dev checked out there are no warnings.
I realise it may be something to do with my setup. I actually downgraded node fro v20 to 418 (stable) with no effect. The build goes to completion but I worry my tests my be invalid. Example:

```
Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

  ╷
1 │ ┌ // This file is a placeholder for the rtl template
2 │ └ @import "template";
  ╵
    build/media_source/templates/site/cassiopeia/scss/template-rtl.scss 1:1  divide()
    media/vendor/bootstrap/scss/mixins/_grid.scss 59:12                      row-cols()
    media/vendor/bootstrap/scss/mixins/_grid.scss 85:13                      @content
    media/vendor/bootstrap/scss/mixins/_breakpoints.scss 68:5                media-breakpoint-up()
    media/vendor/bootstrap/scss/mixins/_grid.scss 72:5                       make-grid-columns()
    media/vendor/bootstrap/scss/_grid.scss 38:3                              @import
    media/vendor/bootstrap/scss/bootstrap.scss 20:9                          @import
    build/media_source/templates/site/cassiopeia/scss/template.scss 14:9     @import
    build/media_source/templates/site/cassiopeia/scss/template-rtl.scss 2:9  root stylesheet
```

**Comment by Fedik** [comment]
It is in Bootstrap SCSS files, we have to wait when they will fix it and do release.

**Comment by Fedik** [comment]
BTW, this should fix it https://github.com/joomla/joomla-cms/pull/41829

**Comment by brianteeman** [comment]
#41829 cannot fix it. it has to be fixed upstream at bootstrap

**Comment by richard67** [comment]
I can confirm that there were several warnings `Deprecation Warning: Passing percentage units to the global abs() function is deprecated.` shown at the 4.4-dev branch in past when running `npm ci`, and that on a current 4.40-dev branch where PR #41829 has been merged, this doesn't happen anymore.

On the 5.0-dev branch these warnings are still shown because 5.0-dev is still on bootstrap 5.3.1. See my comment here: https://github.com/joomla/joomla-cms/pull/41840#issuecomment-1732335429

Shall we leave this issue open until that has been fixed?

Or shall we close it as solved with PR #41829 and rely on the 5.0-dev branch being updated by that?

**Comment by brianteeman** [comment]
> They released fix in 5.3.2 and #41829 updating bootstrap to 5.3.2

sorry i missed that

**Comment by HLeithner** [comment]
[s](https://github.com/joomla/joomla-cms/pull/41899) should fix it.
