### ISSUE TITLE
[4.4.2] Pre-update check: no extensions installed

### ISSUE THREAD

**Issue by wwwiiimmm** [joomla/joomla-cms#42643]
When trying to update from 4.4.2 to 5.0.2 the pre-update check does not find any installed extensions.
I tried it on existing J4 sites with multiple extensions (live+local) and a clean J4 + Akeeba (local).

### Steps to reproduce the issue
Have a Joomla 4.4.2 site.
Have at least 1 extension installed.
Set Update channel to Joomla Next.
Run the pre-update check.

### Expected result
A list of installed extensions with compatibility information for Joomla 5.

### Actual result
A note saying: "No extensions installed."
Eventhough there are.

### System information (as much as possible)
PHP 8.1.26 / MariaDB 10.11.5
PHP 8.2.13 / MariaDB 10.6.15
PHP 8.2.14 / MySQL 8.0.33

**Comment by alikon** [comment]
this pr #42638 should fix this

**Comment by richard67** [comment]
Yes, it should. As a workaround you can apply the change from that PR by editing the “libraries/src/Extension/ExtensionHelper.php” file and doing the same change as shown here https://github.com/joomla/joomla-cms/pull/42638/files . The line numbers max slightly differ if you are on 5.0.2, but the change can be applied on 4.4.2 and 5.0.2.

**Comment by wwwiiimmm** [comment]
Thank you. This solved this issue.
The extension pre-update check now displays as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42643">issues.joomla.org/tracker/joomla-cms/42643</a>.</sub>

**Comment by nsheehan** [comment]
This is closed but still an issue. I have 6 sites at 4.4.2 and on all the version 5 check fails to detect and scan extensions. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42643">issues.joomla.org/tracker/joomla-cms/42643</a>.</sub>

**Comment by richard67** [comment]
@nsheehan See my comment above: https://github.com/joomla/joomla-cms/issues/42643#issuecomment-1887692670 . You can manually apply the change from the linked pull request to fix it on your site. The fix will then be included in the versions 4.4.3 and 5.0.3 in February.
