### ISSUE TITLE
[5.1.0_Beta2] SQL Error on Update to J5.1.0_Beta2

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#43151]
### Steps to reproduce the issue

1. Clone a site with J5.0.3
2. Download J5.1.0_Beta2 update ZIP
3. Start manual update by "Upload and Install" the downloaded file

### Expected result

The update runs smoothly.

### Actual result

The update fails (or seems to fail) with an SQL error:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/57380151-1328-41ee-9dc1-7090deba54b9)

The update log reveals more information:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/9b3628dd-b80d-434e-96f1-510cbe0f3fb8)

The database needs to be repaired:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/6a63dddc-6ce0-4030-944e-237a71916d76)

Database repair is marked as successful
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/6f1f0d67-e150-4f99-9002-c91a1b01c341)

Frontend and backend seem to work without issues.

### System information (as much as possible)

J5.0.3
PHP 8.3.3
MySQL 8.0.33

**Comment by alikon** [comment]
should be fixed by #42988

**Comment by richard67** [comment]
Yes, that is definitely the same issue.

Closing as already solved with #42988 .

**Comment by dautrich** [comment]
I don't know whether it adds more information to the test, but I repeated the test with some more attention to update sources. When I started the update process to J5.1._beta2 were two entries for Joomla! Core (IDs 1 and 104 in the screenshot).

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/406cfd6e-8c37-49dc-9e90-fe37a7017e9e)

**Comment by richard67** [comment]
Hmm, my fix was included in Beta 2, and here the update was made to Beta 2, so either the change to the SQL script made by my PR has not been applied before it was run (but it should have been), or there is still an issue with that SQL statement after my fix.

Reopening.

**Comment by richard67** [comment]
I think the problem is the insert statement before the update statement which I had fixed with my PR. Will check tomorrow, and if my assumption is right I will make a PR.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43169 . Thanks in advance.
