### ISSUE TITLE
Login Menu Item issues

### ISSUE THREAD

**Issue by JoomFX** [joomla/joomla-cms#7204]
There are two issues with the Login Menu item. These are reproducible in both 3.3.6 and 3.4.1 (clean installation).

#### First Issue
1. Create a Login Menu Item
2. Set the "Access Level" to "Guest"
3. Set the "Login Redirect" to "index.php"
4. Login on the front end and you will get the following error:

*You are not authorised to view this resource.*

#### Second Issue
1. Create a Login Menu Item
2. Set the "Access Level" to "Guest"
3. Set the "Login Redirect" to some other page, for example "index.php/component/tags/tag/2-joomla" (this is a valid URL with the default installation with English Sample Content).
4. Login on the front end and you will be forwarded to a wrong URL - the "login" word will always be added at the end of the URL, for example:

*index.php/component/tags/tag/2-joomla/login*

This was also reported in the [forum](http://forum.joomla.org/viewtopic.php?f=706&t=889228).

**Comment by brianteeman** [comment]
Please can you retest with the current staging release which you can
download from here
https://github.com/joomla/joomla-cms/archive/staging.zip

As there were some issues with the redirect on login which should have been
resolved now

On 19 June 2015 at 12:19, Ivo Valkov <notifications@github.com> wrote:

> There are two issues with the Login Menu item. These are reproducible in
> both 3.3.6 and 3.4.1 (clean installation).
> First Issue
>
>    1. Create a Login Menu Item
>    2. Set the "Access Level" to "Guest"
>    3. Set the "Login Redirect" to "index.php"
>    4. Login on the front end and you will get the following error:
>
> *You are not authorised to view this resource.*
> Second Issue
>
>    1. Create a Login Menu Item
>    2. Set the "Access Level" to "Guest"
>    3. Set the "Login Redirect" to some other page, for example
>    "index.php/component/tags/tag/2-joomla" (this is a valid URL with the
>    default installation with English Sample Content).
>    4. Login on the front end and you will be forwarded to a wrong URL -
>    the "login" word will always be added at the end of the URL, for example:
>
> *index.php/component/tags/tag/2-joomla/login*
>
> This was also reported in the forum
> <http://forum.joomla.org/viewtopic.php?f=706&t=889228>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7204>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by JoomFX** [comment]
Thanks for the reply Brian.

I just tested it with the staging release and none of these two issues are fixed.

The redirect issue you are talking about is probably https://github.com/joomla/joomla-cms/pull/6542 .
But it is for the Login Module, not for the Menu Item.

**Comment by infograf768** [comment]
Confirmed here.
What happens in First case is that login through menu item 
=> if redirect is set to "index.php"
redirects to the logout view => here: index.php?option=com_users&view=login&Itemid=233 ) 
=> if redirect is not set, it redirects to the profile view.

As user is no more a "guest" the logout view having the same access as login, it is not displayed and one gets the error.

**Comment by mahagr** [comment]
Similar one (specified in the link to Gantry issue above) is the fact that copying URLs from frontend doesn't work:

    index.php/using-joomla/

will point to:

  index.php/using-joomla/login

Both of the "side effects" are caused from the same "feature" as the links go through JRoute and ```index.php?``` makes Joomla to think that they are non-SEF urls.

**Comment by conconnl** [comment]
I just checked this issue in the staging. (Latest build)

When I create the "index.php?option=com_users&view=login" menu item and I configure a redirect URL after login using "/index.php/article" or any other SEF or None-SEF existing URL, then I receive the "You are not authorised to view this resource." when I use full url "http://domain.com/index.php/article" then everything works as it should.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7204">issues.joomla.org/joomla-cms/7204</a>.</sub>

**Comment by conconnl** [comment]
@brianteeman can you look at this issue?

The redirecting issue as described by @JoomFX is still happening in Joomla (Tested in 3.6 Beta 2)
Next to this: When you have used the "Internal URL" option and you want to switch to the "Menu item" option, you will receive an error that only one of the values may filled, but you would aspect that the value is cleaned when you switch to the other option when you save the menu. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7204">issues.joomla.org/joomla-cms/7204</a>.</sub>

**Comment by infograf768** [comment]
Not easy to clean the value. Patch welcome...

**Comment by andrepereiradasilva** [comment]
### First Issue

Still happens on latest staging, but you can now choose a menu item in the selector.

### Second Issue

Unable to reproduce on latest staging.

**Comment by brianteeman** [comment]
I am closing this as the first issue is easily resolved using the selector<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7204">issues.joomla.org/joomla-cms/7204</a>.</sub>
