### ISSUE TITLE
Bug in com_contact

### ISSUE THREAD

**Issue by PhM1936** [joomla/joomla-cms#8051]
In admin / Composants / Fiches de contact / Paramètres / Listes / Champ de filtre / Masquer, the button's background is green instead of red.
The result is that it does not work. The cause is that the html is
In admin / Composants / Fiches de contact / Paramètres / Listes / Champ de filtre / Masquer, the button's background is green instead of red.
The result is that it does not work. The cause is that the html is
label class="btn active btn-success" for="jform_filter_field1">Masquer</label
instead of
label class="btn active btn-danger" for="jform_filter_field1">Masquer</label
but I dont know where it lies.
Up to you …

**Comment by zero-24** [comment]
@PhM1936 this is allready fixed in staging and gets out with 3.4.5 see: https://github.com/joomla/joomla-cms/pull/8015

Thanks for your report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8051">issues.joomla.org/joomla-cms/8051</a>.</sub>

**Comment by n9iels** [comment]
I tested this (before you said it was already fixed), but the bug still appears on my test location. (Latest version of staging)

**Comment by zero-24** [comment]
hmm sorry i'm going to reopen.

**Comment by n9iels** [comment]
Seems like the bug still appear because the menu parameter en and the component options parameters have the same name.
When I check the output of the parameter via:
`<?php echo $this->params->get('filter_field'); ?>`

The output is <i>hide</i>.
I will make a PR with a solution

**Comment by PhM1936** [comment]
A french expert wrote me :
L'erreur se cache dans le fichier \administrator\components\com_contact\config.xml
la valeur du champ filter_field pour masquer est à hide alors qu'elle devrait être à 0
Code:

<field
   name="filter_field"
   type="radio"
   class="btn-group btn-group-yesno"
   default="1"
   description="JGLOBAL_FILTER_FIELD_DESC"
   label="JGLOBAL_FILTER_FIELD_LABEL"
   >
      <option value="1">JSHOW</option>
      <option value="0">JHIDE</option>        
   </field>

It works and the button become red but does not get out the word "Filtre" in tne front-end …<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8051">issues.joomla.org/joomla-cms/8051</a>.</sub>

**Comment by n9iels** [comment]
I can't reproduce the issue with color buttons. The PR I made solves the issue with the filter field that won't hide. But the color of the buttons is good on my test location

**Comment by PhM1936** [comment]
The color of the button is OK in the back-end, but the word "Filtre" does not disappear in front-end.

**Comment by n9iels** [comment]
Can you please explain witch word you mean? My French is not quite good, so if you can provide a screenshot in English it should be useful :)

**Comment by PhM1936** [comment]
On the front-end (page "contacts of a categorie") you can see the word "Filtre" on the screenshot. I feel it sholuld deappear when the button in the back-end is red : no ?

![filtre](https://cloud.githubusercontent.com/assets/13435124/10412793/65b023d4-6f91-11e5-9afd-dbebb8d77384.png)

**Comment by PhM1936** [comment]
I also wishe to cancel the left column "Nombre 0 1 2" … How ?

**Comment by n9iels** [comment]
The word "filte" is not from the Joomla! Core. I think there is a template override active.
For other support questions and a sulution for this problem, please use the support form. http://forum.joomla.org

Since there is a pull request for this bug, and it is successfully tested twice this issue can be closed.
Thanks reporting!
