### ISSUE TITLE
Ordering in list views inconsistent

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8463]
Most screens have a single select for ordering eg option=com_users&view=users
but the following have two - one for the direction and one for the column to order by

administrator/index.php?option=com_users&view=groups
administrator/index.php?option=com_users&view=levels
administrator/index.php?option=com_users&view=notes

**Comment by zero-24** [comment]
Confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8463">issues.joomla.org/joomla-cms/8463</a>.</sub>

**Comment by Bakual** [comment]
I remember discussing this in another PR already.
Personally I would prefer the two select approach for all views. Imho that's easier to use since the lists are shorter.

**Comment by brianteeman** [comment]
@andrepereiradasilva do you think you could take a look at this one please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8463">issues.joomla.org/joomla-cms/8463</a>.</sub>

**Comment by richard67** [comment]
@brianteeman @Bakual @zero-24 @andrepereiradasilva 

Since I was involded in testing @andrepereiradasilva's PRs I can say the ordering inconsistencies mentioned above is solved with following PRs (note the status):

administrator/index.php?option=com_users&view=groups #9093 = merged
administrator/index.php?option=com_users&view=levels #9092 = RTC
administrator/index.php?option=com_users&view=notes #9091 = RTC

**Comment by andrepereiradasilva** [comment]
Yes, those PR was exactly to bring some consistency to the search tools across com_users administrator list views.

For other components, there are also already PR for:

- [com_checkin] checkin view https://github.com/joomla/joomla-cms/pull/8854 = RTC
- [com_cache] cache view https://github.com/joomla/joomla-cms/pull/9121 - RTC
- [com_menus] menus view https://github.com/joomla/joomla-cms/pull/8842 = Merged
- [com_tags] tags view https://github.com/joomla/joomla-cms/pull/9094 = Merged
- [com_installer] update view https://github.com/joomla/joomla-cms/pull/9118 = RTC
- [com_installer] manage view https://github.com/joomla/joomla-cms/pull/9106 = Merged | https://github.com/joomla/joomla-cms/pull/9139 = RTC
- [com_installer] discover view https://github.com/joomla/joomla-cms/pull/9114 = RTC
- [com_installer] languages view https://github.com/joomla/joomla-cms/pull/9089 = RTC
- [com_installer] updatesites view https://github.com/joomla/joomla-cms/pull/9107 = Merged | https://github.com/joomla/joomla-cms/pull/9139 = RTC
- [com_templates] style and templates views https://github.com/joomla/joomla-cms/pull/9090 = RTC
- [com_languages] installed view https://github.com/joomla/joomla-cms/pull/9101 = RTC
- [com_languages] languages view https://github.com/joomla/joomla-cms/pull/9099 = Merged

**Comment by richard67** [comment]
So in total 11 RTCs to be merged for having it nice and consistent and not buggy in Beta3 ... or RC ... hope they will make it.

**Comment by andrepereiradasilva** [comment]
yes but there are some yet inconsistent. Some have bugs, other still have the old filters/search logic.
Example: com_languages overrides view.

**Comment by richard67** [comment]
Sure ... but I would estimate you have reduced the number of inconsistent and buggy views from some 70% or 80% to some 10% ... and you fixed the most frequently used ones ... from my point of view worth a special note in the release notes.

But thanks for the hint so all can keep in mind that there is still something to be done and help with that by testing (and maybe coding too if you are too busy to do all alone).

**Comment by andrepereiradasilva** [comment]
Update:
- [com_users] groups view #9093 = Merged
- [com_users] levels view #9092 = Merged
- [com_users] notes view #9091 = Merged

So this issue can be closed IMHO.

**Comment by brianteeman** [comment]
Thanks - I forgot I still had to merge the PR when I checked this issue. Thanks for doing all of this - really appreciate it. Another ticket closed - woohoo

**Comment by richard67** [comment]
#9091 and #9092 meanwhile are merged too, so the things mentioned by this issue here are solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8463">issues.joomla.org/joomla-cms/8463</a>.</sub>
