### ISSUE TITLE
Can't log into Admin Backend

### ISSUE THREAD

**Issue by bostmaguy** [joomla/joomla-cms#8766]
If I upgrade to 3.4.7, it won't let me log into the backend. I get an "invalid security token" error message. No error log is being produced on the server either in the admin folder or the root directory. I had to find my 3.4.5 to 3.4.6 update and manually FTP everything to my site to fix the problem. They should keep this update on the server for people who are also having this issue. Other people are reporting it here as well.

**Comment by photodude** [comment]
"invalid security token" error message can happen with any version of Joomla. I can't remember the specifics of why, If I remember right it was something to do with your browser. Once you get the message you just need to do a hard refresh of the page. usually just removing the index.php from the admin url in the address bar and so that your just left with [your domain]/administrator 
press enter and you should be able to log in.

**Comment by photodude** [comment]
On a side note, considering this is a session issue... I wonder if there is some relation to this other session related issue. https://github.com/joomla/joomla-cms/issues/8757

**Comment by fedeverdi** [comment]
Same issue for me...

**Comment by PhilETaylor** [comment]
Clear your cookies and try again. 
Clear your database table #__sessions and try again
Post results here.

**Comment by PhilETaylor** [comment]
What PHP version?
What web server are you using, and version (apache/nginx ubuntu/centos) ?
What session handler are you using?
Whats your session time?

**Comment by photodude** [comment]
@PhilETaylor I have see this issue in every Joomla version since 1.6
happens with IE, Chrome, Firefox, Edge
every php version 5.3→5.6
apache servers
WebServer to PHP Interface	cgi-fcgi
MySQL
database session handler

I just had this come come up 30 seconds ago when I checked what session handler we use (Joomla default database session handler)

Setting | Value
------------ | -------------
PHP Built On | Linux lamp x86_64
Database Version | 5.5.42-cll-lve
Database Collation | utf8_general_ci
PHP Version | 5.6.16
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.4.7
Joomla! Platform Version | 13.1.0
User Agent | Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/47.0.2526.106** Safari/537.36


Following the steps I listed in the post above, the issue goes away (until the message comes up again and I have to repeat the steps again).

**Comment by malaiselvan** [comment]
Me too having the same problem after upgrading to Joomla 3.4.7 on my localhost

I was doing some development on my custom component and all of a sudden it throws 'Invalid Token' when I try to login from front-end.  No luck and I am not able to login :-(

Joomla 3.4.7
Windows 8.1
Xampp 3.2.1

**Comment by wilsonge** [comment]
We've just created a 3.4.8 Release Candidate Package (https://github.com/joomla/joomla-cms/releases/tag/3.4.8-rc). Some of these issues are not reliable - so just give it a try and see if you come across any issues :)

**Comment by stevensandberg** [comment]
I have cleared my cache on FF as well as on Chrome, went into the database and changed my password and also created a new superuser but still I'm getting the "invalid token" message when I try to login

Cleared database table #__session
Joomla 3.4.8 (the error started when I updated from 3.4.6 to 3.4.7)
Php. 5.3.1.9
Apache 2.2.23
MySQL 5.5.27
Session handler Database
session time 180 (yeah I know thats too ong)

**Comment by PhilETaylor** [comment]
clear your COOKIES (not just your cache) in your browser.

**Comment by stevensandberg** [comment]
Did that and still doesn’t work…

**Comment by photodude** [comment]
Try Clearing your sessions table in your database.

**Comment by stevensandberg** [comment]
Did it, unfortunately didn’t work….

**Comment by photodude** [comment]
Try downloading the full Joomla! 3.4.8 install (not the upgrade packages) and copy the files over the top of your site (be sure to skip or remove the install folder and install files).

**Comment by AFlorencia** [comment]
I'm facing this error after updating to 3.4.8
This happens when someone is trying to login the administrator area or navigating the frontend.
I don't know if is a bad server configuration or what. 
I've cleaned the cookies, session table is empty also. 

Warning: base64_decode() has been disabled for security reasons in /home/traductionis1896/public_html/site/libraries/joomla/session/session.php on line 658

Fatal error: Call to a member function get() on a non-object in /home/traductionis1896/public_html/site/libraries/joomla/session/session.php on line 499

Fatal error: __clone method called on non-object in /home/traductionis1896/public_html/site/libraries/joomla/session/session.php on line 386<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8766">issues.joomla.org/joomla-cms/8766</a>.</sub>

**Comment by PhilETaylor** [comment]
"base64_decode() has been disabled for security reasons "

Get a better web host. No, get a reputable web host. Even the bad web hosts know not to disable base64_decode() for security reasons - absolutely pathetic!

**Comment by instance** [comment]
LOL they might as well disconnect their server from the net for "security reasons".

**Comment by AFlorencia** [comment]
They enabled it again. I' not sure what will I do with more than 60 Joomla sites on the same server...But it's working now. Argentina's rules: If it doesn't work, drop it! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8766">issues.joomla.org/joomla-cms/8766</a>.</sub>

**Comment by stevensandberg** [comment]
Yeah did that and that also did not work, it actually screwed up the the hole site… :-(
 Still having the problem though!!

**Comment by syntaxerror** [comment]
I'm facing the same problem on 1 site, of several, and I'm not able to figure out where it's coming from. There is two Joomla sites on the same hosting account, same server environment, just separated web roots. The one being OK is built on 3.x, the problematic one has previously been updated/migrated from 2.5. I can't see any extensions influencing on sessions, especially not for both admin and site, as login is broken for both.

Clearing browser, session table, cache folders, and also turning of cache doesn't change anything. Even changing computer doesn't make any difference.

**Comment by PhilETaylor** [comment]
To get to the bottom of this this Im offering to look into this for FREE for you. Please send me your site details using the form at https://fix.myjoomla.com/now and I'll take a look for FREE - note who I am. I'm pretty darn sure this will not be a Joomla issue at all.

**Comment by photodude** [comment]
Interestingly, I once again got the "The most recent request was denied because it contained an invalid security token. Please refresh the page and try again" message in J3.4.8.

Suspected replication steps,
1. Login to joomla admin (with a short session)
2. Let your session expire and get yourself droped back to the login screen 
3. Put your computer to sleep/hibernate
3. When your well past the session expire time, wake up your computer
4. From the open browser tab with the login screen try loging in again

As always, removing the `/index.php` from the url and pressing `enter` will force a reload of the page and session allowing login

**Comment by PhilETaylor** [comment]
I would say that is perfectly expected behaviour as the cookies you have are expired but yet you are trying to use them!!!

**Comment by PhilETaylor** [comment]
I should point out that your "security token" (for CSRF protection) and your Session token/cookie - are two different things...

**Comment by syntaxerror** [comment]
Yeah, the "issue" of @photodude isn't the same as @bostmaguy and others are facing after the update.

Regarding debugging I "sadly" don't have a site to offer any longer, as I finally got it working. Not sure how yet, but there seems like there was some leftovers and duplicates from Akeeba (like FOF listed with two versions). After uninstalling Admin Tools and Backup, I removed the duplicates/leftovers, before reinstalling them. After that the update didn't cause any token trouble?!

Will try to replicate it on a backup restored to alternative location when (if) I get any time for it in the new year...

For the record, the message displayed is from the lang def JINVALID_TOKEN

**Comment by photodude** [comment]
@syntaxerror from the language files, 
JINVALID_TOKEN="The most recent request was denied because it contained an **invalid security token**. Please refresh the page and try again."

Note: you can't "refresh" the page with the browser refresh button or by hitting the f5 key.
you will be blocked from loging in, stuck on a **white screen** with only this message. Effectively unable to login to the site.
You can however force a **hard refresh** by removing `/index.php` and hitting enter, at which point you will be logged in (no retyping of the user name and password)

**Comment by syntaxerror** [comment]
No, it's not the same thing you're talking about. And no there is no way to do any hard refresh etc. on this issue. As I mentioned, the "issue" you described above isn't the same. And from the responses around, your "solution" doesn't help. No offence, just stating it.

Btw! In frontend JINVALID_TOKEN is simply displayed as "Invalid Token". I just mentioned the def in case anyone would like to peek at the code, to see where and when it's triggered. I'm well aware of the translations of it. :)

**Comment by PhilETaylor** [comment]
ok I just investigated one of these "I cant login" issues for a client 

If you are having issues logging in, please, edit your /configuration.php and tell me (here in the issue) what your setting is for 

```	public $session_handler = 'database';```

Please also confirm or deny if your web host is Siteground.

**Comment by stevensandberg** [comment]
Hi Phil, 
I have: 	public $session_handler = 'database’;
And my host is not siteground, its: keurig online

**Comment by PhilETaylor** [comment]
Thanks - Im investigating an issue with the memcached session handler at the moment - but if you are set to database then thats not your issue - my previous offer to investigate on your site for free stands.

**Comment by stevensandberg** [comment]
Super, thanks! Ill send you the details through the link you sent me tomorrow. 

Have a great new years eve!

**Comment by photodude** [comment]
@syntaxerror from everything I can tell it's triggered by [com_login at line 50](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_login/controller.php#L49-L50)

Basically it's failing the token check from JSession, and exiting with the notice JINVALID_TOKEN
looking at [JSession::checkToken()](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/session/session.php#L309-L335) I would guess something is causing it to fail to get a session resulting in the session not being new [(if session is not new returns false)](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/session/session.php#L318-L329).

**Comment by PhilETaylor** [comment]
@photodude Load up your /administrator/index.php - view the source - find the token in the login form - refresh the page - does the token change or stay the same? It should stay the same... 

If it changes then you have a server session issue - what is your session_handler in /configuration.php

**Comment by PhilETaylor** [comment]
Having investigated (for free) the issues reported by @stevensandberg I'm pleased to report that this is 100% nothing to do with Joomla and 100% the fault of extension developers accessing and manipulating the $_SESSION object directly.

Specifically, the ```antispambycleantalk``` from cleantalk.org with code https://gist.github.com/31bf9127127a9eaf886c is manipulating the $_SESSION object. 

As soon as I disable this extension on this site I was able to login without issue to the Joomla Admin Console and all my session issues were resolved.

![screen shot 2016-01-04 at 13 36 16](https://cloud.githubusercontent.com/assets/400092/12090581/2d0105ea-b2e8-11e5-90cc-3f51e4b4557b.png)

**Comment by PhilETaylor** [comment]
@bostmaguy Are you still having issues or can this issue be closed now?

**Comment by bostmaguy** [comment]
Yes. Once I cleared out the session table in the database, I was able to log into the admin backend. Does anyone know when Joomla is going to have a built-in commenting system as JComments is getting long in the tooth, isn't as mobile-friendly as it should be, and has the worst captcha system that I finally had to shut it off (based on users complaining they couldn't read it) and purchase and install Clean Talk anti-spam plugin for JComments.

**Comment by PhilETaylor** [comment]
Excellent thanks for confirming that its working for you (I'll page @brianteeman who can close this now as I dont have permissions to do that).

I don't believe there are any plans for a commenting solution to be added to Joomla core - however I'm often proved wrong.

**Comment by wilsonge** [comment]
No plans for one as of present or for the foreseeable future

**Comment by photodude** [comment]
@bostmaguy there are a number of other options for comments in the [JED](http://extensions.joomla.org/extensions/extension?searchall=comments&filter%5Btags%5D%5B%5D=&filter%5Bcore_catid%5D=&filter%5Bincludes%5D=&filter%5Bversions%5D=&filter%5Btype%5D=&filter%5Bhasdemo%5D=&order=&filter%5Bnewupdated%5D=&filter%5Bscore%5D=&filter%5Bfavourites%5D=&dir=DESC&limitstart=0&controller=filter&view=extension&layout=list&Itemid=145&clearorders=0&clearfilters=1)

**Comment by RavilN** [comment]
Hi Phil,
I had the same login issue today, after upgrading to 3.4.8. I tried to delete records from jos_session table, tried to connect from the clean VM which has no cookies / browse history in it, the result was the same.
and then I found this discussion, and noticed that cleantalk extension was blamed. I have it installed, so I disabled it from jos_extensions table, and after that the problem disappeared!

Thank you for providing the solution!
Ravil<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8766">issues.joomla.org/joomla-cms/8766</a>.</sub>

**Comment by PhilETaylor** [comment]
@RavilN I'm glad that you got your issue sorted, please be sure to drop a note to the developers of the `antispambycleantalk` plugin to tell them of your frustration - the more people that do that the better the chance their developers will fix their incompatibility.

**Comment by RavilN** [comment]
Done, have sent them the message.

**Comment by safronik** [comment]
Hi everybody. I'm from CleanTalk tech support. Thank @RavilN for letting us know. Our programmers said that we fixed this bug already. To fix that you must delete CleanTalk folder and install [newer version](https://download.cleantalk.org/joomla/joomla25-3x-antispam-3.7.2.zip).

**Comment by nehaharish** [comment]
Thank you so much @PhilETaylor  for solving this problem. The whole day I was looking for the solution after upgrading my site to Joomla 3.4.8 and finally, my problem is gone.
Thanks again.

**Comment by PhilETaylor** [comment]
You're Welcome :) @nehaharish

**Comment by Griefchief** [comment]
Still happening in 2020.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8766">issues.joomla.org/tracker/joomla-cms/8766</a>.</sub>

**Comment by Griefchief** [comment]
Fix is to clear #__session table in db, and change browsers/try in incognito because clearing the cache ("Hard reload") in Chrome doesn't help. What's funny is that the token is actually changing between attempts but it still failed, I was debugging the checkToken function in login() so i can confirm that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8766">issues.joomla.org/tracker/joomla-cms/8766</a>.</sub>

**Comment by PhilETaylor** [comment]
If you are still having a problem in 2020, then the root cause of the problem is probably not the same as this issue.

You are best seeking support from the Joomla Forums￼

**Comment by Griefchief** [comment]
Happens on Joomla 3.9.18 Stable | Amani | 21 April 2020 19:30 GMT So i suspect this is still an issue. Might be a Joomla core issue, or possibly a plugin like Akeeba or similar "security" plugin tampering with the token, and then #__sessions persisting through a database import/export... I experienced this in development too like previous users, not on live.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8766">issues.joomla.org/tracker/joomla-cms/8766</a>.</sub>

**Comment by PhilETaylor** [comment]
Well if you are running out of date and insecure Joomla 3.9.18 you should not be reporting issues. Upgrade to the latest version of Joomla and test with that, if you can replicate a problem, and can reproduce it over and over, then open a new issue here, do not hijack a 5 year old issue that is already PROVEN not to be a Joomla issue, and PROVEN to have been fixed. 

Secondly, please refrain from making wild accusations and assumptions about rock solid award winning software like Akeeba. I can assure you that Akeeba is NOT making any changes to the Joomla Security Session or Token. Read the code. 

Almost 5 years ago I personally looked into this users reported issue, and the problem was with antispambycleantalk from cleantalk.org. This is and was, not, a Joomla core issue.

**Comment by Griefchief** [comment]
All above said, as this issue happens in administrator\components\com_login\controller.php: login() function and it's $this->checkToken('request') line, this smells to me like a Joomla core issue. As mentioned before, I suspect a session from previous dev env got saved in db for admin user and joomla refuses to release that session... So, it looks like a CRSF forgery i suppose, but Joomla should still respect the changing token it itself gives out into the form before trying to login. This is a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8766">issues.joomla.org/tracker/joomla-cms/8766</a>.</sub>

**Comment by PhilETaylor** [comment]
More wild assumptions you are making... Im sorry, Im out.

**Comment by N6REJ** [comment]
@Griefchief as phil said, update your software to the most current version(s) including php, apache & extension(s) and then if you still have an issue you can replicate, open another ticket and tag me personally.
